### ISSUE TITLE
Field constructor 'update' not working

### ISSUE THREAD

**Issue by facundomedica** [web2py/web2py#1432] opened 2016-08-23 18:49 UTC
Hey guys, I'm trying to achieve the auth.signatures's 'modified_on' behaviour without using the auth.signature on my table because I need a reference to this table from auth.user. (So, I can't use auth.signature)

What I want: a field that is updated with the date everytime the record is modified.
What I've tried: `Field('updated_on', 'datetime', update=request.now, writable=False, readable=False),` (I have also tried adding `default=request.now` too).
What it currently does: When I create the record it fills with the current date, but when I modify it, it does not change and its value remains the same.

The web2py book says: **`update` contains the default value for this field when the record is updated.** Which pretty much describes what I'm trying to achieve.

Thanks!

**Comment by niphlod** [comment] 2016-08-24 08:30
if you don't use triggers (which is what the "record archiving" machinery does, in addition to add fields), I think that the problem is that if you declare the field as not writable it doesn't get "filled" with either "default" nor "update" values.

**Comment by facundomedica** [comment] 2016-08-24 13:03
@niphlod thanks for your answer, but I've tried without the `writable=False, readable=False`, and I get exactly the same result.
Thanks again!

**Comment by niphlod** [comment] 2016-09-21 20:48
closing this as I can't reproduce. @facundomedica : feel free to package a minimal app that reproduces the issue on the web2py forum

**Closed by niphlod** 2016-09-21 20:48 UTC
