### ISSUE TITLE
Field constructor - required is broken

### ISSUE THREAD

**Issue by mrdumpty** [web2py/web2py#901] opened 2015-04-05 19:23 UTC
So, it is simple.

db.define_table('table', Field('field', required=True))

This option required=True is totally ignored on 2.10.
You can successfully add records having empty values via forms or via appadmin/insert/db with no errors.

This is highly critical.

**Comment by niphlod** [comment] 2015-04-08 20:11
this is not a bug. little recap (excerpt from the book, chapter 6)

_Notice that requires=... is enforced at the level of forms, required=True is enforced at the level of the DAL (insert), while notnull, unique and ondelete are enforced at the level of the database. While they sometimes may seem redundant, it is important to maintain the distinction when programming with the DAL._

a Field with required=True is only useful to prevent something like (extending a bit your example)

    db.define_table('mytable', 
       Field('req_field', required=True)
       Field('not_req_field')
    )
    db.mytable.insert(not_req_field='abc')
    >>> RuntimeError: Table: missing required field: req_field

if you don't want forms to be submitted when "req_field" holds no value, use either notnull (with a default value of your choosing) or requires=IS_NOT_EMPTY().

I'm closing this, but feel free to add comments if something is wrong

**Closed by niphlod** 2015-04-08 20:11 UTC
Labels: DAL
