### ISSUE TITLE
Formatting not working on db reference (SELECT) 

### ISSUE THREAD

**Issue by misl6** [web2py/web2py#1107] opened 2015-11-19 15:30 UTC
Web2Py Version, etc:
2.11.2-stable+timestamp.2015.05.30.16.33.24
(Running on nginx/1.4.6, Python 2.7.6)
db: postgres

I've defined 2 tables (authors & store_items), and referenced the store_items.author_id to authors table.

When I tried to create a new element in db from w2p appadmin format='%(name)s' the dropdown was loaded correctly, but in appadmin SQLFORM.grid or when I fetch data via a *.select() , format option seems to be ignored and return the ID of referenced authors row.

Example:
```
db.define_table('authors',
            Field('name','string'),
            Field('description','string'),
            Field('bio','string'),
            format='%(name)s')

db.define_table('store_items',
            Field('name','string'),
            Field('description','string'),
            Field('author_id', db.authors,
                        widget=SQLFORM.widgets.options.widget),
            Field('store_file','string'),
            format='%(store_file)s',
            )
```

**Comment by misl6** [comment] 2015-11-23 18:41
Re-tested the same code with:
2.12.3-stable+timestamp.2015.08.19.00.18.03
(Running on nginx/1.4.6, Python 2.7.6) + psql

Now in appadmin SQLFORM.grid all is working fine,still the "issue" about JSON serialization after a *.select()

**Comment by niphlod** [comment] 2015-11-23 20:19
uhm. if you do

db(db.store_items.id>0).select()

it's a DEFAULT and WANTED behaviour to avoid fetching every author referenced to extract the name of the author. You get the "raw" elements that are living in the database. 
Representation (which is the thing that maps "1" to "name of author table whose id is 1") is called by default in forms, because they need to fetch referenced records for 1 record only.
SQLFORM.grid and SQLTABLE (that's the one used in appadmin) on the same end are meant to show a visual representation and since they're usually paged they also do by default the extra step of calling the render() method that turns "1" into your author's name where id == 1.

If you want to return the representation for any .select() on store_items, you should either:
- select the fields you need joining tables EXPLICITELY 
    db(db.author.id == db.store_items.author_id).select(db.store_items.ALL, db.author.name) 
    which is the most cpu-conservative behaviour, and the one I highly recommend
- call .render() on the select(), which will return a generator that will fire a select for every referenced record recursively and apply the rendered representation

Fell free to ask for more details, but I'll close this issue in a few days if no replies come along because it's not a bug.

**Comment by misl6** [comment] 2015-11-24 08:10
@niphlod feel free to close this issue, I've opened this issue mainly for the problem related to SQLTABLE /SQLFORM.grid on Version 2.11.2-stable+timestamp.2015.05.30.16.33.2.

I supposed that .select() only returns RAW data, so I've created a Virtual Field that do the dirty job for me:

```
db.store_items.author_name = Field.Virtual(
    'author_name',
    lambda row: row.store_items.author_id.name)
```

**Comment by niphlod** [comment] 2015-11-24 08:18
just be aware of the performance implications of doing such a thing.

**Closed by niphlod** 2015-11-24 08:18 UTC
