### ISSUE TITLE
Auth.impersonate return statement broken

### ISSUE THREAD

**Issue by michele-comitini** [web2py/web2py#1264] opened 2016-04-05 17:10 UTC
The variable user seems to be undefined on some of the possible execution paths see:

https://github.com/web2py/web2py/blob/master/gluon/tools.py#L4154

**Comment by BuhtigithuB** [comment] 2016-04-05 17:51
Can write a proper test case it you can help me resolve this :
https://groups.google.com/d/msg/web2py-developers/9rDTYKWByqs/6MhoxoskCQAJ

Without being logged in can't test impersonate()...

**Comment by BuhtigithuB** [comment] 2016-04-05 18:18
Here canevas :

    def test_impersonate(self):
        # Create a user to be impersonated
        id = self.db.auth_user.insert(first_name='Omer',
                                      last_name='Simpson',
                                      username='omer',
                                      email='omer@test.com',
                                      password='password_omer',
                                      registration_key='',
                                       registration_id='')

        self.db.commit()
        self.auth.add_group('impersonate')
        self.auth.add_membership(user_id=1,

 group_id=self.db(self.db.auth_user.username == 'user1'
                                                  ).select(
self.db.auth_user.id).first().id)
        self.auth.add_permission(group_id=self.db(self.db.auth_group.role
== 'impersontate'
                                                  ).select(
self.db.auth_group.id).first().id,
                                 name='impersonate',
                                 table_name='auth_user',
                                 record_id=None)
        # Bart login
        self.auth.login_bare(username='user1', password='password_123')
        # Bart impersonate Omer
        self.auth.impersonate(user_id=id)
        self.assertEqual(self.auth.is_impersonating(), True)

**Comment by BuhtigithuB** [comment] 2016-04-05 20:06
I had a look back and this part of tools.py didn't really change regarding
what you mention since 2.9.5

**Comment by michele-comitini** [comment] 2016-04-05 23:00
try impersonate the logged user himself.  Something along the lines:

self.auth.impersonate(self.auth.user_id)

the return statement refers to user.id, but user can be undefined in some cases if you read the if/else sequence you will se some conditions where user is not present.

**Comment by BuhtigithuB** [comment] 2016-04-06 00:58
Yes get some python error when I try to auth.impersonate(user_id=other_user_id) twice... Don't recall the exact error easy to reproduce... Not sure it was raise by impersonate().

**Comment by BuhtigithuB** [comment] 2016-04-06 03:27
I finally found why I was unable to login_bare and been able to create a test_impersonate() test case... 

Here : https://github.com/web2py/web2py/pull/1265

Test is failing, I think, because of the issue you found Michele...

**Comment by BuhtigithuB** [comment] 2016-04-14 04:22
Actually I think the only way impersonate is working is when a user impersonate him self...

**Comment by niphlod** [comment] 2016-09-22 19:14
isn't this fixed  https://github.com/web2py/web2py/commit/fe058bf8179ba279ccf25318f99d21abd825537a ?

@BuhtigithuB : can you check ?

**Comment by BuhtigithuB** [comment] 2016-09-22 19:57
Can try it, but I have really few free time these days, will see if I get
some fuel left late tonigh...

**Comment by BuhtigithuB** [comment] 2016-09-23 17:47
Is trunk broken?

% python web2py.py --run_system_tests
Traceback (most recent call last):
  File "web2py.py", line 33, in <module>
    gluon.widget.start(cron=True)
  File "/web2py_dev/web2py/gluon/widget.py", line 1101, in start
    (options, args) = console()
  File "/web2py_dev/web2py/gluon/widget.py", line 966, in console
    run_system_tests(options)
  File "/web2py_dev/web2py/gluon/widget.py", line 81, in run_system_tests
    sys.exit(ret and 1)
UnboundLocalError: local variable 'ret' referenced before assignment


Richard

On Thu, Sep 22, 2016 at 3:57 PM, Richard Vézina <ml.richard.vezina@gmail.com
> wrote:

> Can try it, but I have really few free time these days, will see if I get
> some fuel left late tonigh...
>

**Comment by niphlod** [comment] 2016-09-23 18:39
seems so. try --with_coverage in the meantime

**Comment by BuhtigithuB** [comment] 2016-09-27 17:00
I manually test impersonating and systme test it and it appears to work
properly, as test succeed ant I can manually double check it...

What does --with_coverage do, I can find any documentation about this
switch...

We can close this ticket if Michele agree as it appears resolved base on
tests results...

But login_bare() still broken

**Comment by niphlod** [comment] 2016-09-27 18:56
--with_coverage enables running tests while recording code coverage, that's the command we use on CI so that can't be broken ^_^

**Comment by BuhtigithuB** [comment] 2016-09-27 19:12
ok...

**Closed** 2016-09-27 19:18 UTC
