### ISSUE TITLE
Admin sr translation

### ISSUE THREAD

**Issue by kelsa-pi** [web2py/web2py#1451] opened 2016-09-18 12:22 UTC
Update translation for sr-lt and st-cr

**Comment by kelsa-pi** [comment] 2016-09-19 14:14
There is errors in Python3 for:
Afrikaanse
<class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\xea' in position 57: ordinal not in range(128)
Bulgarian
<class 'UnicodeEncodeError'> 'ascii' codec can't encode characters in position 15-23: ordinal not in range(128)
Czech
only english text?
France
<class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\xe7' in position 19: ordinal not in range(128)
Polish
<class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\u017c' in position 150: ordinal not in range(128)
Rusian
<class 'UnicodeEncodeError'> 'ascii' codec can't encode characters in position 15-21: ordinal not in range(128)
Slovenian
<class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\u010d' in position 51: ordinal not in range(128)
Serbian
<class 'UnicodeEncodeError'> 'ascii' codec can't encode characters in position 15-20: ordinal not in range(128)
<class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\u0161' in position 32: ordinal not in range(128)

After that language files were damaged and unusable.
ERROR:root:Syntax error in /.../web2py/applications/admin/languages/sr-lt.py (unexpected EOF while parsing (<unknown>, line 15))

For record:
Turkish
OK
Ukrainian
OK

**Comment by ilvalle** [comment] 2016-09-19 18:59
```
Traceback (most recent call last):
  File "/home/ilvalle/web2py/gluon/restricted.py", line 222, in restricted
    exec(ccode, environment)
  File "/home/ilvalle/web2py/applications/admin/views/default/site.html", line 15, in <module>
    {{else:}}
  File "/home/ilvalle/web2py/gluon/globals.py", line 419, in write
    self.body.write(to_native(xmlescape(data)))
  File "/home/ilvalle/web2py/gluon/html.py", line 123, in xmlescape
    return to_bytes(data.xml())
  File "/home/ilvalle/web2py/gluon/languages.py", line 426, in xml
    return str(self) if self.M else local_html_escape(str(self), quote=False)
  File "/home/ilvalle/web2py/gluon/languages.py", line 386, in __str__
    self.T.translate(self.m, self.s))
  File "/home/ilvalle/web2py/gluon/languages.py", line 931, in translate
    lambda: self.get_t(message))
  File "/home/ilvalle/web2py/gluon/languages.py", line 146, in get_from_cache
    result = lang_dict.setdefault(val, fun())
  File "/home/ilvalle/web2py/gluon/languages.py", line 931, in <lambda>
    lambda: self.get_t(message))
  File "/home/ilvalle/web2py/gluon/languages.py", line 816, in get_t
    write_dict(self.language_file, self.t)
  File "/home/ilvalle/web2py/gluon/languages.py", line 336, in write_dict
    repr(Utf8(contents[key]))))
  File "/home/ilvalle/web2py/gluon/packages/dal/pydal/contrib/portalocker.py", line 192, in write
    self.file.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 16: ordinal not in range(128)
```
The above traceback shows that the problem is in pydal portalocker. In py3 (https://github.com/web2py/pydal/blob/master/pydal/contrib/portalocker.py#L173) the file should open with an additional parameter called ```encoding```. @gi0baro would you care about this issue in pydal? In web2py there is this helper https://github.com/web2py/web2py/blob/master/gluon/fileutils.py#L100

**Comment by niphlod** [comment] 2016-09-19 19:41
as the original "to blame being" with portalocker switchs, I wonder myself ..... why doesn't this come up in a unittest!??!?!?

**Comment by niphlod** [comment] 2016-09-19 19:53
@ilvalle : can you take a look to https://github.com/web2py/pydal/pull/420 ? if that's ok we're good.

**Comment by ilvalle** [comment] 2016-09-20 16:33
See the comment on PR. In addition it would be good to have a proper unittest in web2py testing this issue.

**Comment by mdipierro** [comment] 2017-06-20 20:08
@niphlod @ilvalle can this be closed?

**Comment by ilvalle** [comment] 2017-06-22 18:10
@mdipierro you can close this issue.

**Closed** 2017-06-22 21:52 UTC
