### ISSUE TITLE
Mercurial not found, when it is installed

### ISSUE THREAD

**Issue by Euphorbium** [web2py/web2py#943] opened 2015-04-24 07:30 UTC
When I press versioning in the web2py it says "Sorry, could not find mercurial". Mercurial is installed on my system. I am using 
2.10.3-stable+timestamp.2015.04.02.21.42.07
(Running on Rocket 1.2.6, Python 2.7.8)

**Comment by BuhtigithuB** [comment] 2015-04-24 18:17
Do you init your repo in your app??

Richard

**Comment by Euphorbium** [comment] 2015-04-24 20:26
Must I do that myself? I thought web2py would init it automatically if it does not exist, it would be in the spirit of web2py (everything should have sane defaults, automatic migrations and all that.). Even if this is intended behavior, and I am expected to init the repository myself, the error message is really misleading.

**Comment by BuhtigithuB** [comment] 2015-04-24 20:50
I don't know if web2py init or not, but you can try :

cd app
hg init
hg commit -m 'initial init'

Not difficult at all...

Mercurial quisk start : http://mercurial.selenic.com/wiki/QuickStart

NOTE : if hg init above not improve anything you can just deleter app/.hg
to get back at your starting point...

I don't consider web2py should do such a thing for you (I mean init repo),
since initialize a repo also mean to setup Mercurial correctly
particularily .hgrc file which can be global if in ~/.hgrc or local if in
app/.hgrc

Richard

**Comment by Euphorbium** [comment] 2015-04-24 20:59
Well I think it should also provide some kind of sane app/.hgrc file. Otherwise I don't see the point of even having this feature.  At least the error message should be updated to say "Repository not initialized. You should do hg init in application folder " instead of mercurial not found.

**Comment by BuhtigithuB** [comment] 2015-04-26 01:35
And I brew your coffee, cook your eggs and bacon maybe?

:)

Richard

**Comment by uhelp** [comment] 2015-07-23 10:08
Euphoribium is right.

The message is misleading.
And gives bad user experience.
Not very clever to ridicule this issue given the fact that it could be fixed with one or two lines.

greets Kalle

**Comment by BuhtigithuB** [comment] 2015-07-23 13:15
Do you need every app be under version control... Do you want that your
version control system be mercurial by default or you want git... That why
I said that... This is not an issue the choosing spectrum is too broad to
have any kind of default here. Maybe the documentation should be adjust to
explain that...

Here what the documentation says :
http://web2py.com/books/default/chapter/29/03/overview?search=mercurial#Mercurial

Maybe we should have link near the feature pointing to the documentation of
it...

Also, I don't know why we suggest in this documentation to install
mercurial with easy_install since pip is better allowing clean
uninstallation if required...

Anyway... If what it says in this breif documentation is not working, the
documentation should be updated.

Richard

**Comment by Holmes70** [comment] 2016-02-03 09:52
Sooo, it's 2016 and web2py still does a good job at hiding things from the user. Such as mercurial usage. My setup:
OSX 10.11.3
web2py 2.13.4-stable+timestamp.2015.12.26.04.59.39
mercurial 3.6.3
After extensive searching (with quite a bit of false leads, I might add) I found the folder, where web2py stores its apps. That would have been worth at least a footnote in the otherwise exquisite book IMHO.
Then having found this thread and BuhtigithuBs humorous comments I manually setup a repository... but web2py is still of the opinion, that mercurial can't be found. Now what?

**Comment by mdipierro** [comment] 2016-03-19 08:18
That error is caused by a failed import:

try:
    from mercurial import ui, hg, cmdutil
    try:
        from mercurial.scmutil import addremove
    except:
        from mercurial.cmdutil import addremove
    have_mercurial = True
except ImportError:
    have_mercurial = False

...

if not have_mercurial:
    session.flash = T("Sorry, could not find mercurial installed")

Why it is failing to import mercurial for you is not clear. web2py does init the repo if it does not exist. Which is what is asked here.

**Closed by mdipierro** 2016-03-19 08:18 UTC
Labels: enhancement

**Comment by cabrion** [comment] 2016-09-28 11:07
This is happening for me, right from the start, too. 
OS X 10.11.6  
Web2Py 2.14.6 ( via the pre-built Mac App) 
Mercurial 3.9.1 installed via BREW
pip install mercurial 

_Created a simple app in Web2py_ 
cd /Applications/web2py.app/Contents/Resources/TestVersioning
hg init
hg commit -m 'test init'
_still get: Sorry, could not find mercurial installed from web2py_ 
hg add -s *
hg commit -m 'test init2' (failed)
_hg complained about hg config not having a username, so I fixed that in .hgrc_
hg commit -m 'test init2'  (success)
_still get: Sorry, could not find mercurial installed from web2py_

Does the Mac App from web2py perhaps not use the same python as the OS X shell? Maybe a different set of paths for libraries (/usr/local/lib/python2.7/site-packages is where pip installed mercurial)?
