### ISSUE TITLE
python 3 upload getting uft8 invalid continuation byte error

### ISSUE THREAD

**Issue by bjquinn** [web2py/web2py#1717] opened 2017-08-04 21:34 UTC
Environment: 2.15.2-stable+timestamp.2017.07.19.12.18.41 (Running on Rocket 1.2.6, Python 3.6.2)

used example from http://web2py.com/books/default/chapter/29/07/forms-and-validators#SQLFORM-and-uploads

```
db.define_table('person',
    Field('name', requires=IS_NOT_EMPTY()),
    Field('image', 'upload'))
```

```
def display_form():
   record = db.person(request.args(0))
   form = SQLFORM(db.person, record, deletable=True,
                  upload=URL('download'))
   if form.process().accepted:
       response.flash = 'form accepted'
   elif form.errors:
       response.flash = 'form has errors'
   return dict(form=form)
```

Upload a simple text file, all is well.  Upload a binary file of any kind (PDF, MP4, etc.), and get an error like the following:

```
<class 'UnicodeDecodeError'> 'utf-8' codec can't decode byte 0xd3 in position 33402: invalid continuation byte

Traceback (most recent call last):
  File "[redacted]\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 33402: invalid continuation byte
```

Edit: fixed code block formatting

**Comment by leonelcamara** [comment] 2017-08-05 12:47
Can't reproduce this. This works fine for me.

I simply copy pasted your code into the welcome application and run with python 3.

**Comment by bjquinn** [comment] 2017-08-05 15:51
Thanks for trying to reproduce it..  I can't imagine why it would matter, but I tried copy/pasting the code into the welcome app instead of my test app, same result.  Tried mysql as the database, same result.  But it's possible I've messed something up in my web2py setup, and I was using pycharm as my IDE.  So I started from scratch and used only the built in web2py editor.  Here are my steps to reproduce.

- download and unzip web2py source from website
- install python 3.6.2 64 bit for Windows
- cd c:\python36
- python [path to web2py.py]
- put in password, start server, welcome app loads in Chrome browser
- this app -> db model
- copy/paste the following to the bottom of db.py

```
db.define_table('person',
    Field('name', requires=IS_NOT_EMPTY()),
    Field('image', 'upload'))
```

- click save
- hover over left hand toolbar, click on controllers -> default.py
- copy/paste the following after index() and before user()

```
def display_form():
   record = db.person(request.args(0))
   form = SQLFORM(db.person, record, deletable=True,
                  upload=URL('download'))
   if form.process().accepted:
       response.flash = 'form accepted'
   elif form.errors:
       response.flash = 'form has errors'
   return dict(form=form)
```

- click save
- go to http://127.0.0.1:8000/welcome/default/display_form
- type "ascii file" in "name" box
- click choose file button, select a TEXT ONLY file that contains no characters over chr(127)
- click submit
- it works, world peace ensues
- type "binary file" in "name" box
- click choose file button, select a binary file of some kind (PDF, JPG, MP4, etc.)
- click submit
- same error as in original post (though not necessarily with the same "byte" and "position" values, of course), mass hysteria ensues

I should emphasize that I'm using python 3.6.2 for Windows specifically, and probably more importantly, this problem only arises when trying to upload binary files.

**Comment by leonelcamara** [comment] 2017-08-05 21:32
Is it possible this was already fixed in trunk, I was using the github version, can you try that?

**Comment by bjquinn** [comment] 2017-08-06 02:19
I tried that based on your suggestion, but got the same error.  However, admin tool shows version 2.15.2-stable+timestamp.2017.07.19.01.21.31, which I find odd, since that's actually older than my 2.15.2 install.  I just did a git clone https://github.com/web2py/web2py.git followed by git submodule update --init --recursive.  This seems to be the right place to get the latest version, and I even compared the code I got from github versus some changes merged within the last couple days, and all seemed to be correct.

**Comment by leonelcamara** [comment] 2017-08-06 10:57
@bjquinn I managed to reproduce it. Apparently you need to be using the generic.html view for this to happen and I had created a display_form.html view. Thanks!!

**Closed** 2017-08-07 12:08 UTC

**Comment by bjquinn** [comment] 2017-08-07 18:44
Just wanted to chime in and confirm that this did in fact fix the problem for me.  Binary files are now uploadable in python 3 under this set of circumstances without error.  Also tried redownloading the uploaded files, confirmed the files look good, no corruption.  Thanks for the quick help with this!
