### ISSUE TITLE
Setting map_hyphen=True in routes.py breaks codemirror editor

### ISSUE THREAD

**Issue by erikmontes** [web2py/web2py#769] opened 2015-02-03 01:37 UTC
The codemirror breaks once I set the `map_hypen` to `True`.

In my `routes.py` I have:
```python
routers = dict(
    BASE=dict(
        default_application='mycoolapp',
        map_hyphen=True,
    )
)
```

When I try to use the web-based web2py editor it fails to load. 

Looking at the console I see the following 404's:

![screen shot 2015-02-02 at 5 35 16 pm](https://cloud.githubusercontent.com/assets/179356/6012847/ee4b6c12-ab01-11e4-8618-5ddbfbdedb81.png)

The path goes from being an _2.9.5 to -2.9.5 which is expected behavior for the URLS, however because the directory starts with a _ and gets changed to - it causes problem. For example http://localhost:8000/admin/static/**-2.9.5**/js/typeahead.min.js

**Comment by erikmontes** [comment] 2015-02-03 17:43
To add more, I originally tested it on version 2.9.5, but just now tested it on version 2.9.12 and issue still exists.

To reproduce it's quite easy. Download 2.9.12. To the root add routes.py and it place:
```python
routers = dict(
    BASE=dict(
        default_application='mycoolapp',
        map_hyphen=True,
    )
)
```
Now in the admin interface, click on **Reload routes**. Now, try to opening and editing any file using the built-in web2py code editor (uses codemirror).

**Comment by niphlod** [comment] 2015-02-03 21:57
uhm. I'm not convinced this is the right fix.... and in fact I can't reproduce the original issue.......
my "_2.9.5 to -2.9.5" doesn't take place in 2.9.12. The problem is already fixed by https://github.com/web2py/web2py/commit/c0536d3b7487e73599b1f2ae1fcb963b91d41e8f . Can you please doublecheck ?

**Comment by erikmontes** [comment] 2015-02-03 22:15
@niphlod  Hi, I tested it on a fresh copy of 2.9.12. I don't think it has much to do with commit you're referencing. This is a separate issue and goes back to at least 2.9.5. It has nothing to do with allowing *map_hyphen to work for application names* as the commit suggest. 

More system details:
OSX 10.10.2
Python 2.7.6
Web2py 2.9.12

Are you **reloading the routes** after creating the routes.py with the above code in the root dir?

**Comment by niphlod** [comment] 2015-02-04 08:49
yep, I am. Are you ? your problem is with urls in static/ but the code ALREADY skips static . Can you make a test that doesn't involve an app (i.e. from the shell)?

**Comment by erikmontes** [comment] 2015-02-04 17:44
I now feel 100% sure this is a bug. I'm sorry you can't reproduce it, maybe you're not doing something right or I'm not being clear.

I tried to further debug this. I placed a print statement to see what the value of `self.controller` would be.

![screen shot 2015-02-04 at 9 35 30 am](https://cloud.githubusercontent.com/assets/179356/6045721/40e163c8-ac51-11e4-9b9d-643ea36a8388.png)

I then re-started the web2py and refreshed the editor page and checked the terminal and it printed the following values as **self.controller**s:

```shell
default
default
default
default
mercurial
default
default
debug
static
static
static
static
static
static
static
static
default
static
static
static
static
default
static/_2.9.12  <---- look
static/_2.9.12  <---- look
static/_2.9.12  <---- look
default
default
default
default
default
default
default
default
static/_2.9.12  <---- look
static/_2.9.12  <---- look
default
default
static
```
Note that the output contains a couple `static/_2.9.12` as *controllers*.

Now check the current code:
```python
if self.map_hyphen:
    self.controller = self.controller.replace('_', '-') # <--- does not care if static or not, conversion for controller will still take effect, and since `static/_2.9.12` is a "controller" it will get replaced by `static/-2.9.12`
    if self.controller != 'static' and not self.controller.startswith('static/'): # <--- since static check is here
        self.application = self.application.replace('_', '-')
        self.function = self.function.replace('_', '-')
```
In my PR I placed it nested in the static/ check and this has fixed the issue for me:

```python
if self.map_hyphen:
    if self.controller != 'static' and not self.controller.startswith('static/'):
        self.application = self.application.replace('_', '-') 
        self.controller = self.controller.replace('_', '-') # <- will not get touched since it's inside static/ check
        self.function = self.function.replace('_', '-')
```

Let me know if you have more questions. Would like to get the fix merged into master :shipit:

**Comment by niphlod** [comment] 2015-02-04 20:06
if indeed this is happening, the bug is static/something being a controller, not the rewrite logic...

**Comment by niphlod** [comment] 2015-02-04 20:30
imho the error is the way admin is coded.
```python
{{cm=URL('static%s' % (response.static_version and '/_' + response.static_version  or ''),'codemirror')}}
<link rel="stylesheet" href="{{=cm}}/lib/codemirror.css">
```
this doesn't pass through rewrite logic as it should (calling URL('somethingwithaslashinside') is wrong ) and so the controller passed - in some weird occasion - is 'static/_1.2.3'  and everything is screwed up.
Let's patch admin correctly instead of altering the rewrite logic that is perfect.

**Comment by niphlod** [comment] 2015-02-04 20:53
moreover, I found out that there is a subtle bug handling response.static_version and response.static_version_urls ........... stay tuned for a PR that:
- adds response.static_version_urls to admin (so code is decluttered and will ALWAYS work)
- fixes the subtle bug
- cleanups admin
if you trust me, you can go ahead and close this (as already said, the rewrite logic is perfect, it's the use inside admin of URL() that is inherently wrong)... or wait for a PR and test that one.

@mdipierro : please keep this on hold a bit

**Closed** 2015-02-06 00:09 UTC

**Comment by cowbert** [comment] 2015-03-03 22:34
this does not seem to fix the issue with admin. If I set `static_version_urls = False` in `admin/model/0.py`, admin is still appending `_ + static_version` for its static assets. I believe the line 498 in `gluon/globals.py` should be:

    #if self.static_version and not self.static_version_urls
    if self.static_version and self.static_version_urls:

**Comment by niphlod** [comment] 2015-03-03 23:22
did you fetch the latest admin code ?

**Comment by erikmontes** [comment] 2015-03-03 23:37
I just pulled from master and it seems to be ok so far...

**Comment by cowbert** [comment] 2015-03-04 07:24
I just downloaded master.zip from github and admin still wants to read from admin/static/_2.9.12/:

    [04/Mar/2015:02:16:24 -0500] "GET /web2py/admin/static/_2.9.12/js/jquery.js HTTP/1.1" 404 238

I have a custom routes.py, but that shouldn't be interfering, since it is literally copied from the examples:

    BASE = '/web2py'
    routes_in = (
        # do not reroute admin unless you want to disable it
        (BASE + '/admin', '/admin/default/index'),
        (BASE + '/admin/$anything', '/admin/$anything'),
        # do not reroute appadmin unless you want to disable it
        (BASE + '/$app/appadmin', '/$app/appadmin/index'),
        (BASE + '/$app/appadmin/$anything', '/$app/appadmin/$anything'),
        # do not reroute static files
        (BASE + '/$app/static/$anything', '/$app/static/$anything'),
        # reroute favicon and robots, use exable for lack of better choice
        ('/favicon.ico', '/examples/static/favicon.ico'),
        ('/robots.txt', '/examples/static/robots.txt'),
        # do other stuff
        #((r'.*http://otherdomain\.com.* (?P<any>.*)', r'/app/ctr\g<any>')),
        # remove the BASE prefix
       (BASE + '/$anything', '/$anything'),
    )
    routes_out = [(x, y) for (y, x) in routes_in]

**Comment by niphlod** [comment] 2015-03-04 07:55
what's the problem with that ? what resources are not loaded in your case ?

**Comment by cowbert** [comment] 2015-03-04 10:25
The problem is that with static_version_urls=False, admin should not be using static version URLs.

**Comment by niphlod** [comment] 2015-03-04 10:55
ok, the issue you're mentioning comes from 3 set of distinct set of problems:
- an aliasmatch to ([^/]+)/static/(.*) is wrong if you want to support static versioning, and I don't see why you should keep it that way. It's 3 years old.
- static_version_urls works to turn ANY URL('static', 'something') into the "versioned" uri, in addition to the ones generated by response.files
- if you don't remove static_version, you'll still get files generated with response.files with the "versioned" uri, independently from the static_version_urls

**Comment by cowbert** [comment] 2015-03-04 11:01
What I'm saying is I don't want to support static versioning at all, but there is no way to disable it in admin correctly.

**Comment by niphlod** [comment] 2015-03-04 13:11
response.static_version = None
