### ISSUE TITLE
catch psutils error

### ISSUE THREAD

**Issue by ilvalle** [web2py/web2py#959] opened 2015-05-07 12:02 UTC
Even if psutils is present, there is no guarantee that it'll work, it depends on specific information on the host as /proc/meminfo not always available (for example on pythonanywhere).
```
>>> import psutil
>>> psutil.virtual_memory().percent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 1413, in virtual_memory
    return _psplatform.virtual_memory()
  File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 172, in virtual_memory
    f = open('/proc/meminfo', 'r')
IOError: [Errno 2] No such file or directory: '/proc/meminfo'
```

**Comment by niphlod** [comment] 2015-05-07 12:17
it's already fixed on master, even if the machinery code has not been stripped. max_ram_utilization is set to None, so it never triggers the psutil call.

**Comment by ilvalle** [comment] 2015-05-07 12:23
The user has to set max_ram_utilization explicitly? If so, on production it can still raise an exception. isn't it?

**Comment by niphlod** [comment] 2015-05-07 12:27
if he sets the option to store uploads in the uploads/ folder but the underlying system doesn't allow r/w permission, is it also a bug ?
IMHO as it stands right now you can use the feature as long as your plaftorm allows you to, AND only if you want to. 
There's no default value, so by default you don't get any issues. 
You get them if you want to use something you can't use. It's not a bug if your hosting provider doesn't allow accessing the underlying host performance counters...

**Closed** 2015-05-11 07:09 UTC
