### ISSUE TITLE
Invalid reset password

### ISSUE THREAD

**Issue by AnneVerme** [web2py/web2py#1025] opened 2015-07-18 07:38 UTC
I think the cause of the problem is customizing the auth_user table.
I had the following code to customize it:

db.define_table(
    auth.settings.table_user_name,
    Field('title', length=8, default='de heer', requires=IS_IN_SET(['de heer', 'mevrouw'], error_message='Selecteer een aanhef'), widget=bs3radiowidget, label='Aanhef * '),
    Field('first_name', length=32, requires=IS_LENGTH(32, error_message='Lengte overschreidt 32 tekens'), label='Voornaam'),
    Field('familyNamePreposition', length=16, requires=IS_LENGTH(16, error_message='Lengte overschreidt 16 tekens'), label='Tussenvoegsel'),
    Field('last_name', length=64, default='', requires=[IS_LENGTH(64, error_message='Lengte overschreidt 64 tekens'), IS_NOT_EMPTY(error_message='Vul achternaam in')], notnull=True, label='Achternaam * '),
    Field('shortName', length=128, requires=IS_EMPTY_OR(IS_NOT_IN_DB(db, 'auth_user.shortName', error_message='Short name al in database'), IS_LENGTH(128, error_message='Lengte overschreidt 128 tekens')), unique=True, writable=False, readable=False),
    Field('phone', length=16, requires=IS_LENGTH(16, error_message='Lengte overschreidt 16 tekens'), label='Telefoon'),
    Field('email', length=128, default='', requires=[IS_LENGTH(128, error_message='Lengte overschreidt 128 tekens'), IS_EMAIL(error_message='Ongeldig e-mailadres'), IS_NOT_IN_DB(db, 'auth_user.email', error_message='E-mailadres al in database')], notnull=True, unique=True, label='E-mail * '),
    Field('username', length=32, default='', requires=[IS_LENGTH(32, error_message='Lengte overschreidt 32 tekens'), IS_NOT_EMPTY(error_message='Vul gebruikersnaam in'), IS_NOT_IN_DB(db, 'auth_user.username', error_message='Gebruikersnaam al in database')], notnull=True, unique=True, label='Gebruikersnaam * ', writable=False, readable=False),
    Field('password', type='password', length=512, requires=[IS_STRONG(),CRYPT()], label='Wachtwoord * ', writable=False, readable=False),
    Field('nodeID', 'reference nd_node', requires=[IS_EMPTY_OR(IS_IN_DB(db, 'nd_node.id', '%(id)s', zero='Selecteer een node'))], ondelete='CASCADE', label='NodeID * ', writable=False, readable=False),
    Field('registration_key', length=512, default='', writable=False, readable=False),
    Field('reset_password_key', length=512, default='', writable=False, readable=False),
    Field('registration_id', length=512, default='', writable=False, readable=False),
    Field('createdOn', **attributes),
    Field('modifiedOn', update=request.now, **attributes))

## get the custom_auth_table
custom_auth_table = db[auth.settings.table_user_name]
## tell auth to use custom_auth_table
auth.settings.table_user = custom_auth_table
## create all tables needed by auth if not custom tables
auth.define_tables(migrate=False, username=True, signature=False)

While cleaning up my application, and making my code come as close
to what's in the book, I replaced the code above with:

auth.settings.extra_fields['auth_user']= [
  Field('title', length=8, default='de heer', requires=IS_IN_SET(['de heer', 'mevrouw'], error_message='Selecteer een aanhef'), widget=bs3radiowidget, label=''),
  Field('username', length=32, default='', requires=[IS_LENGTH(32, error_message='Lengte overschreidt 32 tekens'), IS_NOT_EMPTY(error_message='Vul gebruikersnaam in'), IS_NOT_IN_DB(db, 'auth_user.username', error_message='Gebruikersnaam al in database')], notnull=True, unique=True, label='Gebruikersnaam * ', writable=False, readable=False),
  Field('vertexID', 'reference vtx_vertex', requires=[IS_EMPTY_OR(IS_IN_DB(db, 'vtx_vertex.id', '%(id)s', zero='Selecteer een vertex'))], ondelete='CASCADE', label='VertexID * ', writable=False, readable=False)]

## create all tables needed by auth if not custom tables
auth.define_tables(migrate=False, username=True, signature=False)

After that the reset_password link no longer worked.  So I guess the issue is related to the way
you customize the auth_user table.

**Comment by mdipierro** [comment] 2015-07-26 19:31
I cannot reproduce this problem but yet I am not using the exact same model you are using because I do not have your custom widget and the other table you reference. Please post a simpler example to reproduce the problem.

**Comment by niphlod** [comment] 2015-09-21 20:26
@AnneVerme : we're going to close this unless a simpler and reproducible problem is posted here in a few days

**Comment by AnneVerme** [comment] 2015-09-22 05:51
Hi Simone,

> @AnneVerme [1] : we're going to close this unless a simpler and
> reproducible problem is posted here in a few days

I believe the problem has been solved, it was related to some of us 
using
an older syntaxis:

https://groups.google.com/forum/?fromgroups=#!topic/web2py/sZKXGvF_Tu4


Kind regards,

Annet

**Closed** 2015-09-22 06:43 UTC
